# Generated by Django 4.2.1 on 2023-06-09 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_delete_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='todo.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.projecttask'),
        ),
    ]
